### ISSUE TITLE
Problem with the last update?

### ISSUE THREAD

**Issue by jcisio** [papajessie/swcpy#1]
I see that all the pages were deleted.

**Comment by jcisio** [comment]
When I try to generate the docs with this version (2026):

```
Traceback (most recent call last):
  File "./swc.py", line 3644, in <module>
    main(sys.argv)
  File "./swc.py", line 1086, in main
    analyse_unit(objects,displayed,i)
  File "./swc.py", line 2009, in analyse_unit
    fill_unit_level(ob,level,subunit)
  File "./swc.py", line 1871, in fill_unit_level
    a[k]=int(v)
ValueError: invalid literal for int() with base 10: 'buffHeroDeathTrooper'
```

Will check later if I have time.

**Comment by jcisio** [comment]
It has been fixed now. Thanks.
